<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>
  <Target Name="CopyToUnity" AfterTargets="Build">
    <ItemGroup>
      <UnityPluginFiles Include="$(OutputPath)*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(UnityPluginFiles)"
          DestinationFolder="$(MSBuildProjectDirectory)/../Unity/Assets/Plugins/Smallworld" />
  </Target>
    <Target Name="CopyToGodot" AfterTargets="Build">
    <ItemGroup>
      <GodotPluginFiles Include="$(OutputPath)*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(GodotPluginFiles)"
          DestinationFolder="$(MSBuildProjectDirectory)/../Godot/libraries" />
  </Target>
</Project>